language: node_js
node_js:
  - "0.8"
  - "0.10"
services:
  - mongodb
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - fabiano@axiomzen.co
    on_success: change
    on_failure: always