// Generated by CoffeeScript 1.6.2
exports.install = function(mongoose) {
  var originalCast, path;

  mongoose.set('debug', true);
  path = 'deleted_at';
  originalCast = mongoose.Query.prototype.cast;
  mongoose.Query.prototype.cast = function(model, obj) {
    if (this.op !== 'remove') {
      obj || (obj = this._conditions);
      this.where(path, {
        $exists: false
      });
    }
    return originalCast(model, obj);
  };
  /*
  original =
    execFind: mongoose.Query::execFind
    exec:     mongoose.Query::exec
    count:    mongoose.Query::count
    findOne:  mongoose.Query::findOne
  
  # mongoose.Query.prototype.includeDeleted = () ->
    # null
  
  exec = (signature, op, cb) ->
    console.log "EXEC(#{arguments.length})", signature, typeof op, typeof cb
    # conds = @[path] || (@_conditions[path] = {})
    # conds.deleted_at = {$exists: false}
    @where(path, {$exists: false})
    if arguments.length  == 2
      original[signature].call(@, op)
    else
      original[signature].call(@, op, cb)
  
  mongoose.Query::execFind = (arg1, arg2) ->
    # console.log "my hacky execFind"
    if arguments.length  == 1 #|| args2 != undefined
      exec.call this, "execFind", arg1
    else
      exec.call this, "execFind", arg1, arg2
  
  mongoose.Query::exec = (arg1, arg2) ->
    # console.log "my hacky exec"
    if arguments.length  == 1 #|| args2 != undefined
      exec.call this, "exec", arg1
    else
      exec.call this, "exec", arg1, arg2
  
  mongoose.Query::count = (arg1) ->
    exec.call this, "count", arg1
  */

  return true;
};
